@baseURL = http://127.0.0.1:8000
@resource = categories

###
# @name auth
POST {{baseURL}}/auth/token
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "secr3t"
}

###
# @name create
POST {{baseURL}}/{{resource}}
Content-Type: application/json
Authorization: Bearer {{auth.response.body.token}}

{
    "title": "My Category 1"
}

###
# @name all
GET {{baseURL}}/{{resource}}
Authorization: Bearer {{auth.response.body.token}}

###
# @name one
GET {{baseURL}}/{{resource}}/{{all.response.body.categories[0].pk}}
Authorization: Bearer {{auth.response.body.token}}

###
# @name update
PUT {{baseURL}}/{{resource}}/{{all.response.body.categories[0].pk}}
Content-Type: application/json
Authorization: Bearer {{auth.response.body.token}}

{
    "title": "My Category 0 (delete)"
}

###
# @name destroy
DELETE {{baseURL}}/{{resource}}/{{all.response.body.categories[0].pk}}
Authorization: Bearer {{auth.response.body.token}}
