@baseURL = http://127.0.0.1:8000
@resource = wallets

###
# @name auth
POST {{baseURL}}/auth/token
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "secr3t"
}

###
# @name create
POST {{baseURL}}/{{resource}}
Authorization: Bearer {{auth.response.body.token}}
Content-Type: application/json

{
    "name": "Wallet 1"
}

###
# @name all
GET {{baseURL}}/{{resource}}
Authorization: Bearer {{auth.response.body.token}}

###
# @name one
GET {{baseURL}}/{{resource}}/{{all.response.body.wallets[0].pk}}
Authorization: Bearer {{auth.response.body.token}}

###
# @name update
PUT {{baseURL}}/{{resource}}/{{all.response.body.wallets[0].pk}}
Authorization: Bearer {{auth.response.body.token}}
Content-Type: application/json

{
    "name": "Wallet 0"
}

###
# @name destroy
DELETE {{baseURL}}/{{resource}}/{{all.response.body.wallets[0].pk}}
Authorization: Bearer {{auth.response.body.token}}
