# Generated by Django 3.2.1 on 2021-05-13 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_wallet_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='wallet.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SplitedLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('number_of_parts', models.PositiveIntegerField()),
                ('day_of_month', models.PositiveSmallIntegerField()),
                ('split_number', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splited_logs', to='wallet.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_deposit_of_transfer', to='wallet.log')),
                ('from_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.category')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.wallet')),
                ('to_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.category')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.wallet')),
                ('withdraw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_withdraw_of_transfer', to='wallet.log')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SplitedLogPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_splited_log_part', to='wallet.log')),
                ('splited_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='wallet.splitedlog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='splitedlog',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splited_logs', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='log',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='wallet.wallet'),
        ),
    ]
